# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  go: circleci/go@1.3.1
jobs:
  build:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      # Necessary to bind-mount /var/run/docker.sock inside the Docker container that's running our build
      # See: https://support.circleci.com/hc/en-us/articles/115015849028-Docker-Daemon-Not-Available
      - setup_remote_docker

      - checkout
        # - go/load-cache
        # - go/mod-download
        # - go/save-cache

      # TODO Add caching like in https://circleci.com/docs/2.0/language-go/
      #- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash .ci/check_for_changelog_in_diff.sh; fi
      - run: scripts/full_build_and_run.sh
