openapi: 3.0.0

info:
  title: Engine API
  version: 0.1.0

paths:
  /engine/info:
    get:
      summary: Get Engine Info
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineInfo'

  /enclaves:
    get:
      summary: Get Enclaves
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  enclave_info:
                    type: object
                    additionalProperties:
                      $ref: '#/components/schemas/EnclaveInfo'
                
    post:
      summary: Create Enclave
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEnclave'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnclaveInfo'
                
    delete:
      summary: Delete Enclaves
      parameters:
        - name: remove_all
          in: query
          required: false
          description: If true, remove all enclaves. Default is false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletionSummary'
                
  /enclaves/historical:
    get:
      summary: Get Historical Enclaves
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnclaveIdentifiers'

  /enclaves/{enclave_identifier}:
    get:
      summary: Get Enclave Info
      parameters:
        - name: enclave_identifier
          in: path
          required: true
          description: UUID, shortened UUID, or name of the enclave
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnclaveInfo'



    delete:
      summary: Destroy Enclave
      parameters:
        - name: enclave_identifier
          in: path
          required: true
          description: UUID, shortened UUID, or name of the enclave
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object

  /enclaves/{enclave_identifier}/logs:
    post:
      summary: Get Service Logs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetServiceLogsArgs'
      parameters:
        - name: enclave_identifier
          in: path
          required: true
          description: UUID, shortened UUID, or name of the enclave
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetServiceLogsResponse'

  /enclaves/{enclave_identifier}/stop:
    post:
      summary: Stop Enclave
      parameters:
        - name: enclave_identifier
          in: path
          required: true
          description: UUID, shortened UUID, or name of the enclave
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object

# =========================================================================================================================
# =========================================================================================================================
# > > > > > > > > > > > > > > > > > > > > > > > > Data Models < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < 
# =========================================================================================================================
# =========================================================================================================================

components:

  schemas:

    EngineInfo:
      type: object
      properties:
        engine_version:
          type: string

    CreateEnclave:
      type: object
      properties:
        enclave_name:
          type: string
        api_container_version_tag:
          type: string
        api_container_log_level:
          type: string
        mode:
          $ref: '#/components/schemas/EnclaveMode'
    
    EnclaveMode:
      type: string
      enum:
        - TEST
        - PRODUCTION
    
    EnclaveContainersStatus:
      type: string
      enum:
        - RUNNING
        - STOPPED
        - EMPTY
    
    ApiContainerStatus:
      type: string
      enum:
        - RUNNING
        - STOPPED
        - NON_EXISTENT

    EnclaveInfo:
      type: object
      properties:
        enclave_uuid:
          type: string
        name:
          type: string
        shortened_uuid:
          type: string
        containers_status:
          $ref: '#/components/schemas/EnclaveContainersStatus'
        api_container_status:
          $ref: '#/components/schemas/ApiContainerStatus'
        api_container_info:
          $ref: '#/components/schemas/EnclaveAPIContainerInfo'
        api_container_host_machine_info:
          $ref: '#/components/schemas/EnclaveAPIContainerHostMachineInfo'
        creation_time:
          $ref: '#/components/schemas/Timestamp'
        mode:
          $ref: '#/components/schemas/EnclaveMode'
          

    EnclaveAPIContainerInfo:
      type: object
      properties:
        container_id:
          type: string
        ip_inside_enclave:
          type: string
        grpc_port_inside_enclave:
          type: integer
        bridge_ip_address:
          type: string

    EnclaveAPIContainerHostMachineInfo:
      type: object
      properties:
        ip_on_host_machine:
          type: string
        grpc_port_on_host_machine:
          type: integer

    EnclaveIdentifiers:
      type: object
      properties:
        enclave_uuid:
          type: string
        name:
          type: string
        shortened_uuid:
          type: string

    EnclaveNameAndUuid:
      type: object
      properties:
        name:
          type: string
        uuid:
          type: string

    DeletionSummary:
      type: object
      properties:
        removed_enclave_name_and_uuids:
          type: array
          items:
            $ref: '#/components/schemas/EnclaveNameAndUuid'

    GetServiceLogsArgs:
      type: object
      properties:
        service_uuid_set:
          type: array
          items:
            type: string
        follow_logs:
          type: boolean
        conjunctive_filters:
          type: array
          items:
            $ref: '#/components/schemas/LogLineFilter'
        return_all_logs:
          type: boolean
        num_log_lines:
          type: integer

    GetServiceLogsResponse:
      type: object
      properties:
        service_logs_by_service_uuid:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/LogLine'
        not_found_service_uuid_set:
          type: array
          items:
            type: string

    LogLine:
      type: object
      properties:
        line:
          type: array
          items:
            type: string
        timestamp:
          $ref: '#/components/schemas/Timestamp'

    LogLineFilter:
      type: object
      properties:
        operator:
          $ref: '#/components/schemas/LogLineOperator'
        text_pattern:
          type: string

    LogLineOperator:
      type: string
      enum:
        - DOES_CONTAIN_TEXT
        - DOES_NOT_CONTAIN_TEXT
        - DOES_CONTAIN_MATCH_REGEX
        - DOES_NOT_CONTAIN_MATCH_REGEX

    Timestamp:
      type: string
      format: date-time
