version: 2.1

orbs:
  npm-publisher: uraway/npm-publisher@0.2.0
  kurtosis-docs-checker: kurtosis-tech/docs-checker@0.2.1

parameters:
  go-version:
    type: string
    default: "1.17"
  build-cache-key-prefix:
    type: string
    default: "go-mod-v1"   # Can bump this version to bust the cache

# NOTE: Because CircleCI jobs run on separate machines from each other, we duplicate steps (like checkout) between jobs. This is because doing the "correct" DRY
#  refactoring of, "one job for checkout, one job for build Docker image, etc." would require a) persisting files between jobs and b) persisting Docker images between
#  jobs. Both are annoying (saving/loading workspaces require re-downloading the workspace over the network, and there doesn't seem to be a good way to do Docker
#  images), so we run everything inside a single job.
# See also: https://discuss.circleci.com/t/can-docker-images-be-preserved-between-jobs-in-a-workflow-without-a-manual-load-save/23388/12
jobs:
  build_container_engine_lib:
    docker:
      - image: "cimg/go:<< pipeline.parameters.go-version >>"

    # Done on 2022-05-15, when the job was 1m30s and CircleCI insights showed that we were maxing out the 'medium' class CPUs
    resource_class: large

    steps:
      - checkout

      # If the only changes are to the docs, don't run the slow (and expensive) code checks
      # `git diff --exit-code` returns 0 exit code if no changes, and 1 if changes
      - run: |
          if git --no-pager diff --exit-code origin/master...HEAD -- . ':!docs'; then
            circleci-agent step halt
          fi
      # Cache our dependencies
      - restore_cache:
          keys:
            - << pipeline.parameters.build-cache-key-prefix >>-{{ checksum "container-engine-lib/go.sum" }}

      - run: |
          git config --global url."https://${KURTOSISBOT_GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          go env -w "GOPRIVATE=github.com/kurtosis-tech/*"
          container-engine-lib/scripts/build.sh
      - save_cache:
          key: << pipeline.parameters.build-cache-key-prefix >>-{{ checksum "container-engine-lib/go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"  # Go module cache on the cimg/go image, as reported by "go env GOMODCACHE"
            - "/home/circleci/.cache/go-build"  # Go build cache on the cimg/go image, as reported by "go env GOCACHE"

workflows:
  build:
    jobs:
      # -- PR check jobs ------------------------------------------
      - kurtosis-docs-checker/check-docs:
          markdown-link-check-config-json: "{}"
          filters:
            branches:
              ignore:
                - master
      - build_container_engine_lib:
          context:
            # This pulls in KurtosisBot's Github token, so that we can read from our private repos
            - github-user
          filters:
            branches:
              ignore:
                - master
      # -- End PR check jobs ---------------------------------------

      # -- Artifact-publishing jobs --------------------------------
      # -- End artifact-publishing jobs ----------------------------