# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks: []

builds:
  - id: api-container-availability-waiter
    main: ./api_container_availability_waiter
    binary: api-container-availability-waiter
    goos:
      - linux # For Alpine Docker image
    goarch:
      - amd64
  - id: api-container
    main: ./api_container
    binary: api-container
    goos:
      - linux # For Alpine Docker image
    goarch:
      - amd64

archives:
  # Disables archive creation
  - format: binary

dockers:
  - id: api-container-image
    dockerfile: api_container/Dockerfile
    image_templates:
      - "{{ .Env.API_IMAGE }}:{{ .Env.FIXED_DOCKER_IMAGE_TAG }}"
      - "{{ .Env.API_IMAGE }}:{{ .Env.AUTOUPDATING_DOCKER_IMAGE_TAG }}"
      - "{{ .Env.API_IMAGE }}:latest"
    ids:
      - api-container
      - api-container-availability-waiter
    goos: linux
    goarch: amd64

release: 
  # No need to publish releases to Github
  disable: true

source:
  # Kurt Core is a private project, and we definitely don't want to release source code
  enabled: false

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.FIXED_DOCKER_IMAGE_TAG }}"
changelog:
  # We manage our own changelog
  skip: true
