# TODO remove startosis from here when its more furnished
run:
  skip-files:
    - "api_container/server/startosis_engine/startosis_interpreter.go"
    - "api_container/server/startosis_engine/startosis_executor.go"

issues:
  exclude-rules:
    - path: "api_container/server/api_container_service.go"
      text: "SA4023"

linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1019' # disable the rule SA1019 - ioutils replaced with os
  gosimple:
    checks:
      - all
      - '-S1009' # disable S1009 - should omit nil check; len() for map[interface]interface{}