# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks: []

# AFTER HOOK TO GENERATE WRAPPER SCRIPT
builds:
  # TODO DELETE THIS WHEN WE NO LONGER HAVE A WRAPPER SCRIPT
  - id: wrapper-generator
    main: ./wrapper_generator
    binary: "{{ .Env.WRAPPER_GENERATOR_BINARY_OUTPUT_FILENAME }}"
    # NOTE: The goos and goarch don't really matter here, because we build this
    #  wrapper script generator binary with --single-target anyways
    goos:
      - "darwin"
    goarch:
      - "amd64"
    # We don't want a unique dist dir so that it's easy to get the filepath to the outputted binary
    no_unique_dist_dir: true
  - id: api-container-availability-waiter
    main: ./api_container_availability_waiter
    binary: api-container-availability-waiter
    goos:
      - linux # For Alpine Docker image
    goarch:
      - amd64
  - id: api-container
    main: ./api_container
    binary: api-container
    goos:
      - linux # For Alpine Docker image
    goarch:
      - amd64
  - id: cli
    main: ./cli
    binary: "{{ .Env.CLI_BINARY_FILENAME }}"
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
  - id: initializer
    main: ./initializer
    binary: initializer
    goos:
      - linux # For Alpine Docker image
    goarch:
      - amd64
  - id: golang-internal-testsuite
    main: ./golang_internal_testsuite
    binary: golang-internal-testsuite
    goos:
      - linux # For Alpine Docker image
    goarch:
      - amd64
dockers:
  # TODO Maybe package the CLI into a Docker image?
  
  - id: api-container-image
    dockerfile: api_container/Dockerfile
    image_templates:
      - "{{ .Env.API_IMAGE }}:{{ .Env.DOCKER_IMAGE_TAG }}"
    ids:
      - api-container
      - api-container-availability-waiter
    goos: linux
    goarch: amd64
  - id: initializer-image
    ids:
      - initializer
    dockerfile: initializer/Dockerfile
    image_templates:
      - "{{ .Env.INITIALIZER_IMAGE }}:{{ .Env.DOCKER_IMAGE_TAG }}"
    goos: linux
    goarch: amd64
  - id: golang-internal-testsuite-image
    ids:
      - golang-internal-testsuite
    dockerfile: golang_internal_testsuite/Dockerfile
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/golang-{{ .Env.INTERNAL_TESTSUITE_IMAGE_SUFFIX }}:{{ .Env.DOCKER_IMAGE_TAG }}"
    goos: linux
    goarch: amd64
    extra_files:
      - golang_internal_testsuite/static_files
  - id: javascript-repl-image
    ids: []
    dockerfile: javascript_cli_image/Dockerfile
    image_templates:
      - "{{ .Env.JAVASCRIPT_REPL_IMAGE }}:{{ .Env.DOCKER_IMAGE_TAG }}"

# In order for releasing-to-Github to work, we have to create these archives
archives:
  - id: cli
    builds:
      - cli
    # Kurtosis is a private repo so we don't want to package any files except the binaries, but GoReleaser by default packages the README, LICENSE, and changelog
    # Worse, setting this to be emptylist won't work because GoReleaser takes emptylist to mean "package the defaults" per:
    #  https://github.com/goreleaser/goreleaser/blob/73641c71ac0d9f78e2409b0cea1bf5b42111b933/internal/pipe/archive/archive.go#L61
    # Therefore, we set this to a glob of files that definitely don't exist
    files:
      - "THIS_FILE_DOES_NOT_EXIST"
    name_template: kurtosis-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}

# In order for Homebrew to work, we have to create a repo where the CLI release artifacts will be uploaded
release:
  github:
    owner: kurtosis-tech
    name: kurtosis-core-release-artifacts

  # NOTE: these are the archive IDs, not the build/binary IDs
  ids:
    - cli

brews:
  - name: cli
    ids:
      - cli
    tap:
      owner: kurtosis-tech
      name: homebrew-tap
    commit_author:
      name: kurtosisbot
    commit_msg_template: "Automated formula update for the CLI, version {{ .Tag }}"
    homepage: "https://www.kurtosistech.com"
    description: "CLI for managing Kurtosis environments."

    # One day, we'll probably want to put a license
    # license: SOME-SPDX-LICENSE

source:
  # Kurt Core is a private project, and we definitely don't want to release source code
  enabled: false

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.DOCKER_IMAGE_TAG }}"
changelog:
  # We manage our own changelog
  skip: true
