openapi: 3.0.0

info:
  title: Logging API
  version: 0.1.0

paths:
  /enclaves/{enclave_identifier}/logs:
    get:
      summary: Get Service Logs
      parameters:
        - $ref: "#/components/parameters/enclave_identifier"
        - $ref: "#/components/parameters/service_uuid_set"
        - $ref: "#/components/parameters/follow_logs"
        - $ref: "#/components/parameters/conjunctive_filters"
        - $ref: "#/components/parameters/return_all_logs"
        - $ref: "#/components/parameters/num_log_lines"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceLogs"

  /enclaves/{enclave_identifier}/services/{service_uuid}/logs:
    get:
      summary: Get Service Logs
      parameters:
        - $ref: "#/components/parameters/enclave_identifier"
        - $ref: "#/components/parameters/service_uuid"
        - $ref: "#/components/parameters/follow_logs"
        - $ref: "#/components/parameters/conjunctive_filters"
        - $ref: "#/components/parameters/return_all_logs"
        - $ref: "#/components/parameters/num_log_lines"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceLogs"

# =========================================================================================================================
# =========================================================================================================================
# > > > > > > > > > > > > > > > > > > > > > > > > Data Models < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < <
# =========================================================================================================================
# =========================================================================================================================

components:
  parameters:
    enclave_identifier:
      name: enclave_identifier
      in: path
      required: true
      description: UUID, shortened UUID, or name of the enclave
      schema:
        type: string

    service_uuid:
      name: service_uuid
      in: path
      required: true
      schema:
        type: string

    service_uuid_set:
      name: service_uuid_set
      in: query
      required: true
      schema:
        type: array
        items:
          type: string

    follow_logs:
      name: follow_logs
      in: query
      required: false
      schema:
        type: boolean

    conjunctive_filters:
      name: conjunctive_filters
      in: query
      required: false
      schema:
        type: array
        items:
          $ref: "#/components/schemas/LogLineFilter"

    return_all_logs:
      name: return_all_logs
      in: query
      required: false
      schema:
        type: boolean

    num_log_lines:
      name: num_log_lines
      in: query
      required: false
      schema:
        type: integer

  schemas:

    ServiceLogs:
      type: object
      properties:
        service_logs_by_service_uuid:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/LogLine"
        not_found_service_uuid_set:
          type: array
          items:
            type: string

    LogLine:
      type: object
      properties:
        line:
          type: array
          items:
            type: string
        timestamp:
          $ref: "#/components/schemas/Timestamp"
      required:
        - line
        - timestamp

    LogLineFilter:
      type: object
      properties:
        operator:
          $ref: "#/components/schemas/LogLineOperator"
        text_pattern:
          type: string
      required:
        - operator
        - text_pattern

    LogLineOperator:
      type: string
      enum:
        - DOES_CONTAIN_TEXT
        - DOES_NOT_CONTAIN_TEXT
        - DOES_CONTAIN_MATCH_REGEX
        - DOES_NOT_CONTAIN_MATCH_REGEX

    Timestamp:
      type: string
      format: date-time
