packageId: github.com/kurtosis-tech/plan-yaml-prac
services:
- uuid: "1"
  name: db
  image:
    name: postgres:alpine
  envVars:
  - key: POSTGRES_USER
    value: tedi
  - key: POSTGRES_PASSWORD
    value: tedi
  - key: POSTGRES_DB
    value: tedi
- uuid: "2"
  name: blob-spammer
  image:
    name: ethpandaops/tx-fuzz:master
  command:
  - apk update && apk add curl jq && current_epoch=$(curl -s http://{{ kurtosis.1.ip_address
    }}:5/eth/v2/beacon/blocks/head | jq -r ".version") && echo $current_epoch && while
    [ $current_epoch != "deneb" ]; do echo "waiting for deneb, current epoch is $current_epoch";
    current_epoch=$(curl -s http://{{ kurtosis.1.ip_address }}:5/eth/v2/beacon/blocks/head
    | jq -r ".version"); sleep 1; done && echo "sleep is over, starting to send blob
    transactions" && /tx-fuzz.bin blobs --rpc={{ kurtosis.1.ip_address }} --sk=["0x12"]
  entrypoint:
  - /bin/sh
  - -c
