packageId: github.com/kurtosis-tech/plan-yaml-prac
services:
- uuid: "1"
  name: db
  image:
    name: postgres:latest
  envVars:
  - key: POSTGRES_USER
    value: tedi
  - key: POSTGRES_PASSWORD
    value: tedi
  - key: POSTGRES_DB
    value: tedi
- uuid: "3"
  name: db2
  image:
    name: postgres:latest
  envVars:
  - key: POSTGRES_DB
    value: '{{ kurtosis.2.code }}'
  - key: POSTGRES_USER
    value: '{{ kurtosis.2.output }}'
  - key: POSTGRES_PASSWORD
    value: tedi
tasks:
- uuid: "2"
  taskType: exec
  command:
  - echo
  - Hello, world
  serviceName: db
  acceptableCodes:
  - 0
