packageId: github.com/kurtosis-tech/plan-yaml-prac
services:
- uuid: 1
  name: db
  image:
    name: postgres:alpine
  envVars:
  - key: POSTGRES_PASSWORD
    value: tedi
  - key: POSTGRES_DB
    value: tedi
  - key: POSTGRES_USER
    value: tedi
tasks:
- uuid: 2
  taskType: exec
  command:
  - echo
  - Hello, world
  serviceName: db
  acceptableCodes:
  - 156
