packageId: github.com/kurtosis-tech/plan-yaml-prac
services:
- name: tedi
  image: ubuntu:latest
  command:
  - cat
  - /root/hi.txt
  envVars:
  - key: PASSWORD
    value: tedi
  ports:
  - name: dashboard
    number: 1234
    transportProtocol: TCP
    applicationProtocol: http
  files:
  - mountPath: /root
    filesArtifacts:
    - uuid: dd21662c2137448d8ba42e50d7f41287
      name: hi-file
filesArtifacts:
- uuid: dd21662c2137448d8ba42e50d7f41287
  name: hi-file
  files:
    clear: ""
    get: ""
    items: ""
    keys: ""
    pop: ""
    popitem: ""
    setdefault: ""
    update: ""
    values: ""
