packageId: github.com/kurtosis-tech/plan-yaml-prac
services:
- uuid: "2"
  name: database
  image:
    name: postgres:latest
  envVars:
  - key: VAR_1
    value: '{{ kurtosis.1.output }}'
  - key: VAR_2
    value: '{{ kurtosis.1.code }}'
tasks:
- uuid: "1"
  taskType: sh
  command:
  - echo some stuff
  image: badouralix/curl-jq
