packageId: github.com/kurtosis-tech/plan-yaml-prac
services:
- uuid: 1
  name: database
  image:
    name: postgres:latest
- uuid: 2
  name: tedi
  image:
    name: ubuntu:latest
  envVars:
  - key: DB_URL
    value: '{{ kurtosis.1.ip_address }}'
