name: Require version bump if breaking change

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  do-not-merge-if-breaking:
    name: apidiff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go install golang.org/x/exp/cmd/apidiff
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'tmp'
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - run: apidiff -m $GITHUB_WORKSPACE/api/golang $GITHUB_WORKSPACE/tmp/api/golang
